### ISSUE TITLE
egress rule to api server not working because of calico?

### ISSUE THREAD

**Issue by KEZHwMlXV1vFzs6QvY8v5WjX5** [projectcalico/libcalico-go#1060]
## Expected Behavior
pod wants to reach the api server port 443

## Current Behavior
dial tcp 172.31.0.1:443: i/o timeout

## Possible Solution
It looks like there is none, yet but here is a description that matches our situation:

https://stackoverflow.com/questions/50102943/how-to-allow-access-to-kubernetes-api-using-egress-network-policy

## Steps to Reproduce (for bugs)
use a default deny egress rule in a namespace like this

  - ports:
    - port: 443
      protocol: TCP
    to:
    - namespaceSelector: {}
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
    to:
    - namespaceSelector: {}

## Context
we want to allow a pod to reach the apiserver.

## Your Environment

* libcalico-go version: 

CNI plugin version: v3.2.3
quay.io/giantswarm/kube-controllers:v3.2.3

* Operating System and version: stable coreos

**Comment by caseydavenport** [comment]
> namespaceSelector: {}

This clause isn't going to work for the apiserver, since it is likely running with `hostNetwork: true`.

NP selectors/namespaceselectors only apply to pods which are not sharing the host network.

You can probably use something like Calico `GlobalNetworkPolicy` and `HostEndpoints` to do this, though.
