### ISSUE TITLE
Takes a long time to find and allocate a new IPAM block

### ISSUE THREAD

**Issue by YanzhaoLi** [projectcalico/libcalico-go#1236]
When I was doing scale test, the rateLimiter blocked the request of ipblock.
The timeout of  cni-plugin is hardcoded 90s, could I change the config.QPS or config.Burst  by environment variable or any other ways?

BTW, I noticed the ipam client query each IPblock and test its validation. 
Why not request all IPblocks at one time and find the valid IPblock. And then ask kube-apiserver to update the ipblock resource( need a way to beat race condition)

**Comment by caseydavenport** [comment]
@YanzhaoLi sorry for the delay - could you share more about what type of scale test you were doing? What is the setup like? Is this on a real cluster or simulated in some way? How many pods / nodes / etc?

We could adjust the burst probably for the CNI plugin (I don't think a config option exists today). But we've tested this in the past at scale and have had no issue with the current settings so I'm curious how you managed to hit the limit.

**Comment by YanzhaoLi** [comment]
50000pods on 500nodes,  IPBlockSize=64, 1024 IPBlocks. 
At worst, to query for a valid IPblock, the IPAMclient would query for 1024 times. 
For current RateLimiter(5, 100), with the timeout 90s, the IPAMclient can handle at most 5 * 90 + 100 = 450 times of queries.

**Comment by caseydavenport** [comment]
This is our current QPS configuration: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/k8s.go#L263-L271

> Why not request all IPblocks at one time and find the valid IPblock. And then ask kube-apiserver to update the ipblock resource( need a way to beat race condition)

Yeah, this might fix the issue here. It would mean we increase API server load in _some_ scenarios, where only one or two requests would suffice, but fix the worst-case scenario. 

I would very much like to fix this by reducing the number of API requests needed rather than increasing burst / QPS. 

Just to make sure I understand, the scenario you're encountering is when allocating a new IPAM block? Or are we getting ratelimited for IP allocation from existing blocks as well?

**Comment by caseydavenport** [comment]
I think this PR will probably help a lot: https://github.com/projectcalico/libcalico-go/pull/1248
