### ISSUE TITLE
Help text doesn't include list of valid resources

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#126]
The help text for `get | create | delete` doesn't include the list of valid objects.

e.g `policy, profile, workloadendpoint, hostendpoint, bgppeer` etc.

**Comment by robbrockbank** [comment]
The `get` and `delete` do include already - because the resource type is one of the parameters in the command.

I hadn't included in the other commands because you can only feed in files and so it's necessary to understand the file format.    That said - in hindsight, it's useful to still know which resource types you can manage through each of the commands so definitely worth including.

**Comment by robbrockbank** [comment]
It does now.
