### ISSUE TITLE
IPAM().AutoAssign should return error when no addresses allocated

### ISSUE THREAD

**Issue by mihgen** [projectcalico/libcalico-go#202]
When there is no pool available, no IP address is returned. See example invocation at https://github.com/projectcalico/calico-cni/blob/master/ipam/calico-ipam.go#L84:
```
assignedV4, assignedV6, err := calicoClient.IPAM().AutoAssign(assignArgs)
```

In calico-cni, it leads to crash (log below), due to an attempt to access first element of empty list (see https://github.com/projectcalico/calico-cni/blob/master/ipam/calico-ipam.go#L91, and issue https://github.com/projectcalico/calico-cni/issues/188 for further details).

This issue would not appear, if error was returned. Request, in fact, didn't succeed - so I think that we need to return error in this case. Your opinion folks?

```
Oct 17 06:25:13 node97 kubelet[19531]: ERROR: logging before flag.Parse: E1017 06:25:13.191945  102004 ipam.go:475] Error in auto assign: Block affinity (%!s(*string=0xc4202b1ad0)) does not match provided (node97)
Oct 17 06:25:13 node97 kubelet[19531]: ERROR: logging before flag.Parse: W1017 06:25:13.191981  102004 ipam.go:270] Failed to assign IPs in pool 10.233.64.0/18: Block affinity (%!s(*string=0xc4202b1ad0)) does not match provided (node97)
Oct 17 06:25:13 node97 kubelet[19531]: ERROR: logging before flag.Parse: E1017 06:25:13.194090  102004 ipam.go:465] Error getting block: resource does not exist: {{{fd80:24e2:f998:72d6:9314:8a74:cea7:2cc0 ffffffffffffffffffffffffffffffc0}}}
Oct 17 06:25:13 node97 kubelet[19531]: ERROR: logging before flag.Parse: W1017 06:25:13.194148  102004 ipam.go:270] Failed to assign IPs in pool fd80:24e2:f998:72d6::/64: resource does not exist: {{{fd80:24e2:f998:72d6:9314:8a74:cea7:2cc0 ffffffffffffffffffffffffffffffc0}}}
Oct 17 06:25:13 node97 kubelet[19531]: Calico CNI IPAM assigned addresses IPv4=[] IPv6=[]
Oct 17 06:25:13 node97 kubelet[19531]: panic: runtime error: index out of range
Oct 17 06:25:13 node97 kubelet[19531]: goroutine 1 [running]:
Oct 17 06:25:13 node97 kubelet[19531]: panic(0x9af180, 0xc42000a0b0)
Oct 17 06:25:13 node97 kubelet[19531]: #011/usr/local/go/src/runtime/panic.go:500 +0x1a1
Oct 17 06:25:13 node97 kubelet[19531]: main.cmdAdd(0xc42025fc70, 0x3, 0xa6e86a)
Oct 17 06:25:13 node97 kubelet[19531]: #011/go/src/github.com/projectcalico/calico-cni/ipam/calico-ipam.go:91 +0xe40
Oct 17 06:25:13 node97 kubelet[19531]: github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel.(*dispatcher).pluginMain(0xc42021bec0, 0xab62b0, 0xab62b8, 0xc4200a2058)
Oct 17 06:25:13 node97 kubelet[19531]: #011/go/src/github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:155 +0x303
Oct 17 06:25:13 node97 kubelet[19531]: github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel.PluginMain(0xab62b0, 0xab62b8)
Oct 17 06:25:13 node97 kubelet[19531]: #011/go/src/github.com/projectcalico/calico-cni/vendor/github.com/containernetworking/cni/pkg/skel/skel.go:188 +0xd6
Oct 17 06:25:13 node97 kubelet[19531]: main.main()
Oct 17 06:25:13 node97 kubelet[19531]: #011/go/src/github.com/projectcalico/calico-cni/ipam/calico-ipam.go:20 +0x39
Oct 17 06:25:13 node97 kubelet[19531]: E1017 06:25:13.198981   19561 cni.go:255] Error adding network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
Oct 17 06:25:13 node97 kubelet[19531]: E1017 06:25:13.198999   19561 cni.go:209] Error while adding to cni network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
```

**Comment by gunjan5** [comment]
One case to consider is when `AutoAssign` requests 257 IPs from a pool that is of size 256, so `AutoAssign` would return 256 IPs. Currently, it just prints an Info log: https://github.com/projectcalico/libcalico-go/blob/master/lib/client/ipam.go#L279
`Auto-assigned 256 out of 257 IPv4s` which is not a complete failure since it assigned all the IPs that were requested except 1. 

One possible fix in the CNI code could be that it checks for `len(assignedV4)==1`
https://github.com/projectcalico/calico-cni/blob/master/ipam/calico-ipam.go#L90
Same for `assignedV6` at line 95 since it's possible that pool could have run out of IPv4 addresses but not IPv6, and if it returned an error `calico-ipam` would just return at https://github.com/projectcalico/calico-cni/blob/master/ipam/calico-ipam.go#L86
 even though the IPv6 address was assigned. 

I'm leaning towards having a custom error type returned when IPAM allocates fewer IPs than requested, and then the caller can check which of the IPs are fewer than requested and take appropriate action. 

@robbrockbank @tomdee what do you guys think?

**Comment by mihgen** [comment]
> I'm leaning towards having a custom error type returned when IPAM allocates fewer IPs than requested, and then the caller can check which of the IPs are fewer than requested and take appropriate action.

Yeah - something like a struct with error text message, actual number of ipv4 allocated, actual number of ipv6 allocated?

**Comment by jellonek** [comment]
```
fasaxc> jell: IIRC the contract for AutoAssign is to assign at most the asked for number of addresses.  It may return fewer if the datastore is under contention.
fasaxc> I.e. if you really need an address you need to check how many you got and keep asking for more until you get one (with timeout at that higher level if it consistently fails).
fasaxc> errors are reserved for bugs/datastore errors
```
IMO this is quite different situation because both lists of assigned addresses were empty so contract was broken - there was returned no single one assigned address.

Still this can be ok for `libcalico-go` - but should be verified on `calico-cni` like in https://github.com/projectcalico/calico-cni/pull/190

**Comment by caseydavenport** [comment]
Just reading this now - isn't the problem that AutoAssign should return an error when no pool is available?

Looks like the CNI code expects AutoAssign to return an error, but it isn't being hit? https://github.com/projectcalico/calico-cni/blob/master/ipam/calico-ipam.go#L86 

The mechanism for this already exists - AutoAssign should just return an error when it encounters one. . .

**Comment by caseydavenport** [comment]
If I understand correctly, this was fixed in the CNI plugin by checking the number of returned IP addresses (which is the way AutoAssign is meant to be used).

Closing - let me know if there is something else here, and I can re-open!
