### ISSUE TITLE
k8s driver incorrectly reports host-networked or IP-less pod, during resync snapshot

### ISSUE THREAD

**Issue by neiljerram** [projectcalico/libcalico-go#358]
The k8s backend has a bug whereby IP-less (or host-networked) pods are not excluded as they should be when processing a resync snapshot, whereas they are (correctly) excluded when the client calls List() to list workload endpoints, or when the watcher detects a pod creation or update outside resync.

More detail:

- During resync, `performSnapshot` calls `syn.kc.clientSet.Pods("").List(opts)` and then `syn.kc.converter.podToWorkloadEndpoint(&po)` for each returned pod.

- `podToWorkloadEndpoint` checks `if c.hasIPAddress(pod)`, but only to decide whether to map that IP address, not to suppress the conversion as a whole.

- Probably there should be an `isCalicoPod(&pod)` check added before calling `podToWorkloadEndpoint`.

**Comment by neiljerram** [comment]
(CC @caseydavenport @fasaxc )

**Comment by caseydavenport** [comment]
Yep.  In master we're at least checking for hostNetwork, but we're not checking the IP address yet.

https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/syncer.go#L428

I think just replacing that check with `isCalicoPod` would do the trick.

**Comment by caseydavenport** [comment]
@gunjan5 this is probably a very easy way to change some code in the kdd if you're interested :)

**Comment by neiljerram** [comment]
Thanks @caseydavenport .

Since writing the above, though, I've uncovered a worry: does `applyWorkloadEndpoint` (in k8s.go) still make sense?

- It's documented as "patches the existing Pod to include an IP address, if one has been set on the workload endpoint", and if that's really (and only) what it's used for, it seems to me that it doesn't make sense, because a Pod _without_ an IP address would never get as far as being known to any client as a WorkloadEndpoint - and so there's no way that a client could then add an IP to that endpoint.

- On the other hand, `applyWorkloadEndpoint` is used by the cni-plugin, and it looks like this is for purposes other than setting the IP field.  In that case, perhaps it's just the commenting of `applyWorkloadEndpoint` that needs updating.

**Comment by caseydavenport** [comment]
@neiljerram in an ideal world we make "applyWorkloadEndpoint" a no-op.  Unfortunately, we need to do this as a workaround for an upstream k8s issue - see here: https://github.com/kubernetes/kubernetes/issues/39113#issuecomment-268728626

The CNI plugin builds an endpoint with the assigned IP address and applies it here: https://github.com/projectcalico/cni-plugin/blob/master/k8s/k8s.go#L211

It's quite a bit of magic right now - all of the WorkloadEndpoint fields are generated directly from the Pod API object that backs it, so apply doesn't need to actually update anything.  The only reason for its existence is so the CNI plugin can write the IP address back to the API before it would have been otherwise (by the kubelet), thus reducing time-to-connectivity since Felix sees that WorkloadEndpoint's IP address that much sooner.

We suspect this might have an impact on high scale clusters (many more API writes), but without this workaround there is a performance impact on low-scale cluster (multiple seconds time to connectivity). 

Hopefully that all made sense!

**Comment by neiljerram** [comment]
@caseydavenport That very nearly makes complete sense to me.  The missing piece is: where does that CNI plugin k8s.go code get "the Pod API object that backs it" from?

As long as the answer is somehow other than through libcalico-go's KubeClient, I'm happy.  (Because if it was through KubeClient, I wouldn't understand how it will continue to be possible to get a Pod that doesn't yet have an IP.)

**Comment by caseydavenport** [comment]
See this guy: https://github.com/projectcalico/libcalico-go/blob/master/lib/backend/k8s/k8s.go#L458

The pod name is encoded in the workload ID.  When we do the apply, we grab the Pod from the API and update the status.

**Comment by neiljerram** [comment]
Thanks @caseydavenport for your last comment, but that's still not what I meant.  I've worked out the last bit myself now, and it looks good, but for the record:

- What I meant was, what is the source of the information on the RHS of these assignments:

		// Create the endpoint object and configure it.
		endpoint = api.NewWorkloadEndpoint()
		endpoint.Metadata.Name = args.IfName
		endpoint.Metadata.Node = hostname
		endpoint.Metadata.Orchestrator = orchestrator
		endpoint.Metadata.Workload = workload
		endpoint.Metadata.Labels = labels

- The immediate answer is that they are parameters on the CmdAddK8s call, that is invoked from calico.go:CmdAdd, from calico.go:main.

So the (IP-less) pod information comes from whatever it is in the k8s ecosystem that invokes the CNI plugin, and

- it obviously must be reliable for the pod information at that point to be IP-less, because it's the CNI plugin's job to generate and add the IP

- that invocation isn't through KubeClient, so I can stop worrying about it being broken by the proposed KubeClient change for this issue.

Happy now!

**Comment by caseydavenport** [comment]
Fixed by #362
