### ISSUE TITLE
Add label/selector support for other resources (IP Pools, BGP Peers etc.)

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#421]
Enhancement suggestion.

Would be useful to add label or selector support to other resource types.
e.g. Nodes w/ labels, BGP Peers using selectors to select nodes
e.g. IP Pools with selectors to select nodes for affinity

**Comment by xychu** [comment]
For me, it seem to be like three steps to accomplish this:

1. add `Labels` in `unversioned.ObjectMetadata` so that all the objects could be defined with labels;
2. accept query params in REST api and transfer to selector so that `List` interface should use a List Options with selector to filter the target objects;
3. update `calicoctl` to support selectors

**Comment by caseydavenport** [comment]
We've done this in Calico v3.3 for BGP peers!

:raised_hands:
