### ISSUE TITLE
Restrict IP Pool with an un-strict CIDR to be created

### ISSUE THREAD

**Issue by xychu** [projectcalico/libcalico-go#425]
## Expected Behavior

Once a IP Pool with an un-strict CIDR(e.g. 10.2.2.0/16) been created,
the `bird` will be not running and this IP Pool cannot be delete.

Maybe we should prevent such IP Pool to be created.

## Steps to Reproduce (for bugs)

1. create ippool with cidr: 10.2.2.0/16
2. try to delete it, failed with:
    
   ` DEBU[2017-05-25T15:11:47+08:00] Get Key: /calico/v1/ipam/v4/pool/10.2.0.0-16 ` 
   ` DEBU[2017-05-25T15:11:47+08:00] Key not found error ` 
    `ERRO[2017-05-25T15:11:47+08:00] [DELETE] /v2/ippools/10.2.2.0/16 GOT error: resource does not exist: IPPool(cidr=10.2.0.0/16) `

3. the `bird` failed to start, logs:

    `[root@sryslave1 calico]# tail -f -n 40 bird/current`                                                                                                                                                                                        
    `2017-05-25_06:51:05.90235 bird: /etc/calico/confd/config/bird_ipam.cfg, line 10: Invalid network prefix: 10.2.2.0/16.`                                                                                                                      
    `2017-05-25_06:51:06.90458 bird: /etc/calico/confd/config/bird_ipam.cfg, line 10: Invalid network prefix: 10.2.2.0/16.`

## Your Environment

* libcalico-go version: 12e511c
* Operating System and version:
* Link to your project (optional):

**Comment by caseydavenport** [comment]
Looks to me like there are two bugs here:

### Not properly handling pools that aren't in CIDR notation

> /etc/calico/confd/config/bird_ipam.cfg, line 10: Invalid network prefix: 10.2.2.0/16.

### Not sending through the correct delete to etcd

> [DELETE] /v2/ippools/10.2.2.0/16 GOT error: resource does not exist: IPPool(cidr=10.2.0.0/16)

This seems to indicate that we're sending through a delete to `/v2/ippools/10.2.2.0/16` rather than `/v2/ippools/10.2.0.0-16` which is what we should be doing.



I think we should either:
- Normalize all IPPool requests so that everything is represented in correct CIDR format.
- OR, prevent people from creating Pools with invalid CIDRs.

@robbrockbank WDYT?  I'm not sure which is nicer.  The first option is less onerous on users and isn't an API change, but means that what you put into the API isn't the same as what you get out.

**Comment by robbrockbank** [comment]
The original intention was to normalize the request - but the more I think about this the more I think we shouldn't really be changing the value of an index field (so what you configure is not what you get).

So, I think policing against this is probably the correct fix.  Given that an incorrect configuration would have broken a calico/node deployment I think we can safely make this change.

**Comment by robbrockbank** [comment]
Fixed by #426
