### ISSUE TITLE
network policy named ports are not supported

### ISSUE THREAD

**Issue by redbaron** [projectcalico/libcalico-go#770]
## Expected Behavior
Named ports in network policy are supported 

## Current Behavior
Named ports cause explicit panic if not numeric: https://github.com/projectcalico/libcalico-go/blob/b2eca7082417b2fd940ab3eaac6af793d7cb06ff/lib/backend/k8s/conversion/conversion.go#L549-L553

## Context
Kubernetes spec says following regarding `port` field in network policy rules:

Field |  Description
-- | --
port | The port on the given protocol. This can either be a numerical or  **named port on a pod**. If this field is not provided, this matches all  port names and numbers.

Related: https://github.com/projectcalico/felix/issues/1685

**Comment by caseydavenport** [comment]
Named ports weren't introduced into Calico until v3.0.

I think we should leave https://github.com/projectcalico/felix/issues/1685 open because v2.6 shouldn't crash when given a named port.

However, I'm going to close this guy since v3.0 includes named port support, implemented [here](https://github.com/projectcalico/libcalico-go/blob/b2eca7082417b2fd940ab3eaac6af793d7cb06ff/lib/numorstring/port.go#L64).
