### ISSUE TITLE
Don't require write access to pods (use pod/status)

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#888]
## Expected Behavior

What's described here: https://github.com/kubernetes/kubernetes/pull/65022#discussion_r195087195

Should be an easy fix. Will required adjusting our RBAC yamls once implemented. 

## Current Behavior

We write to the pod API.

## Possible Solution

Write to the pod/status subresource instead. 

## Context

What's described here: https://github.com/kubernetes/kubernetes/pull/65022#discussion_r195087195

## Your Environment

* libcalico-go version:
* Operating System and version:
* Link to your project (optional):

**Comment by fasaxc** [comment]
Looks like key difference with the example in that thread is setting the subresource.  I think that maps to this incantation on the go API:
```
pod, err := c.clientSet.CoreV1().Pods(ns).Patch(wepID.Pod, types.StrategicMergePatchType, patch, "status")
```
I had tried patching the status before (but possibly without calling it out as a subresource?) in order to try the patch to the PodIP field directly.  That didn't work because kubelet clobbers it.  I don't think I've tried the exact incantation above (with `", status"`); seems promising.

One thing to be wary of: retesting this might require a scale run; wasn't that the only way we hit this problem?

**Comment by caseydavenport** [comment]
> retesting this might require a scale run; wasn't that the only way we hit this problem?

It's where the impact was most prominent for sure, but I think the risk is fairly low. I'd be happy to make this change without a scale re-test specifically for it.
